spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/expense_manager
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 2KB
      location: ${java.io.tmpdir}

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours in milliseconds

app:
  cors:
    allowed-origins: http://localhost:3000

expense:
  attachment:
    allowed-types: application/pdf,image/jpeg,image/png
    max-size: 5MB
  approval:
    threshold: 1000.00 # Expenses above this amount require manager approval

logging:
  level:
    root: INFO
    com.zidioDev.ExpenseManager: DEBUG
    org.springframework.security: INFO

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 38393188104-hjhjldmdgn25knqc7k99mdj97849k1b7.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          github:
            client-id: Ov23liozze1fyVQXPsWE
            client-secret: 085912321630d77ce35e8d7c3a71d287bc03b808
            scope:
              - user:email
              - read:user

---
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_manager_dev

app:
  cors:
    allowed-origins: "*"

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

app:
  cors:
    allowed-origins: "*"

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

server:
  port: ${PORT:8080}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

logging:
  level:
    root: WARN
    com.zidioDev.ExpenseManager: INFO 